- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Change to directory backup
      command: "docker exec awx_postgres pg_dump -U awx -Fc awx > `date +%m.%d.%y_%H.%M.%S`_awx_db.dump"
      args:
        chdir: /u01/backup
      register: tobackup
