- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! {{ vnombre }}"
    - name: Change to directory backup
      command: sh awx_backup.sh
      args:
        chdir: /u01/backup
      register: tobackup
